dist: bionic
language: python
python:
  - "3.8"
before_script:
  - "export PYTHONPATH=$PYTHONPATH:$(pwd)"
install:
  - "pip install -U \"discord.py[voice] @ git+https://github.com/Rapptz/discord.py@master\" \"astroid @ git+https://github.com/PyCQA/astroid@master\" \"pylint @ git+https://github.com/PyCQA/pylint@master\""
  - "pip install -U $(find requirements -name *.txt -print | sed -e 's/^/-r /' | tr '\n' ' ')"
script:
  - "pytest -vs --cov=jishaku --cov-report term-missing:skip-covered"
  - "flake8 ."
  - "pylint jishaku"
  - "isort . --check-only --recursive"
  - "python ./setup.py sdist bdist_egg bdist_wheel"
  - "cd docs && make html"
